# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/digitalocean/godo
%global goipath         github.com/digitalocean/godo
Version:                1.65.0

%gometa

%global common_description %{expand:
DigitalOcean Go API client.}

%global golicenses      LICENSE.txt
%global godocs          CONTRIBUTING.md CHANGELOG.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        DigitalOcean Go API client

License:        MIT

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/google/go-querystring/query)
BuildRequires:  golang(golang.org/x/oauth2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Sep 03 2021 Mikel Olasagasti Uranga <mikel@olasagasti.info> - 1.65.0-1
- Initial package

